import json

notebook_cells = [
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import sys\n",
            "\n",
            'venv_path = os.path.abspath(r"..\\granola.ai\\Lib\\site-packages")\n',
            "if venv_path not in sys.path:\n",
            "    sys.path.insert(0, venv_path)",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import warnings\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "from sklearn.model_selection import train_test_split, GridSearchCV\n",
            "from sklearn.preprocessing import LabelEncoder, StandardScaler\n",
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.metrics import classification_report, confusion_matrix\n",
            "\n",
            'warnings.filterwarnings("ignore")\n',
            'pd.set_option("display.max_columns", None)\n',
            'pd.set_option("display.width", 1000)\n',
            'sns.set_theme(style="darkgrid")',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            'base_dir = os.path.dirname(os.getcwd()) if os.path.basename(os.getcwd()) == "notebooks" else os.getcwd()\n',
            'data_path = os.path.join(base_dir, "data", "dataset.csv")\n',
            "df = pd.read_csv(data_path)",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            'df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"], format="%Y-%m-%d")\n',
            'df["First Response Time"] = pd.to_datetime(df["First Response Time"], format="%Y-%m-%d %H:%M:%S", errors="coerce")\n',
            'df["Time to Resolution"] = pd.to_datetime(df["Time to Resolution"], format="%Y-%m-%d %H:%M:%S", errors="coerce")\n',
            "\n",
            'df_ticket = df.drop(columns=["Ticket ID"])\n',
            'df_ticket["Resolution"] = df_ticket["Resolution"].fillna("None")\n',
            'df_ticket["First Response Time"] = df_ticket["First Response Time"].fillna("No response")\n',
            'df_ticket["Time to Resolution"] = df_ticket["Time to Resolution"].fillna("No resolution")\n',
            'df_ticket["Customer Satisfaction Rating"] = df_ticket["Customer Satisfaction Rating"].fillna("No rating")',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "age = []\n",
            'for i in df_ticket["Customer Age"]:\n',
            "    if i <= 30:\n",
            '        age.append("Young Customer")\n',
            "    elif 30 < i < 55:\n",
            '        age.append("Middle Age Customer")\n',
            "    else:\n",
            '        age.append("Old Customer")\n',
            'df_ticket["Type of Customer"] = age\n',
            "\n",
            "chance_r = []\n",
            'for i in df_ticket["Time to Resolution"]:\n',
            '    if i == "No resolution":\n',
            '        chance_r.append("No")\n',
            "    else:\n",
            '        chance_r.append("Yes")\n',
            'df_ticket["Resolution_bin"] = chance_r',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            'df_resolution = df_ticket[df_ticket["Resolution_bin"] == "Yes"].copy()\n',
            "\n",
            "rating = []\n",
            'for i in df_resolution["Customer Satisfaction Rating"]:\n',
            "    if isinstance(i, (int, float)) and i <= 2:\n",
            '        rating.append("Low")\n',
            "    elif isinstance(i, (int, float)) and i == 3:\n",
            '        rating.append("Medium")\n',
            "    else:\n",
            '        rating.append("High")\n',
            'df_resolution["Type of rating"] = rating',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Separate target and features (Target removed to prevent leakage)\n",
            'y_raw = df_resolution["Type of rating"]\n',
            "X_raw = df_resolution.drop(\n",
            "    columns=[\n",
            '        "Customer Name",\n',
            '        "Customer Email",\n',
            '        "Customer Age",\n',
            '        "Product Purchased",\n',
            '        "Date of Purchase",\n',
            '        "Ticket Description",\n',
            '        "Ticket Status",\n',
            '        "First Response Time",\n',
            '        "Time to Resolution",\n',
            '        "Response",\n',
            '        "Resolution_bin",\n',
            '        "Resolution",\n',
            '        "Customer Satisfaction Rating",\n',
            '        "Type of rating",\n',
            "    ],\n",
            '    errors="ignore",\n',
            ")\n",
            "\n",
            "# Train-test split before encoding\n",
            "X_train, X_test, y_train_raw, y_test_raw = train_test_split(X_raw, y_raw, test_size=0.2, random_state=0)",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Encode categorical features\n",
            "feature_cols = X_train.columns\n",
            "for col in feature_cols:\n",
            "    encoder = LabelEncoder()\n",
            "    X_train[col] = encoder.fit_transform(X_train[col].astype(str))\n",
            "    X_test[col] = X_test[col].astype(str).map(lambda s: '<unknown>' if s not in encoder.classes_ else s)\n",
            "    encoder.classes_ = np.append(encoder.classes_, '<unknown>')\n",
            "    X_test[col] = encoder.transform(X_test[col])\n",
            "\n",
            "# Feature Scaling (Crucial for Logistic Regression solvers)\n",
            "scaler = StandardScaler()\n",
            "X_train = scaler.fit_transform(X_train)\n",
            "X_test = scaler.transform(X_test)\n",
            "\n",
            "# Encode target\n",
            "target_encoder = LabelEncoder()\n",
            "y_train = target_encoder.fit_transform(y_train_raw)\n",
            "y_test = target_encoder.transform(y_test_raw)",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Hyperparameter grid\n",
            "param_grid = [\n",
            "    {\n",
            "        'penalty': ['l2'],\n",
            "        'C': [0.001, 0.01, 0.1, 1, 10, 100],\n",
            "        'solver': ['lbfgs', 'newton-cg'],\n",
            "        'max_iter': [1000]\n",
            "    },\n",
            "    {\n",
            "        'penalty': ['l1', 'l2'],\n",
            "        'C': [0.001, 0.01, 0.1, 1, 10, 100],\n",
            "        'solver': ['liblinear', 'saga'],\n",
            "        'max_iter': [1000]\n",
            "    }\n",
            "]\n",
            "\n",
            "# Running grid search with n_jobs=1 to avoid worker crash\n",
            "grid_search = GridSearchCV(\n",
            "    estimator=LogisticRegression(),\n",
            "    param_grid=param_grid,\n",
            "    cv=5,\n",
            "    scoring='f1_weighted',\n",
            "    n_jobs=1,\n",
            "    verbose=1\n",
            ")\n",
            "\n",
            "grid_search.fit(X_train, y_train)\n",
            "\n",
            "print('--- Hyperparameter Tuning Results ---')\n",
            "print('Best Parameters:', grid_search.best_params_)\n",
            "print('Best CV Score:', grid_search.best_score_)\n",
            "\n",
            "# Fit and predict with best estimator\n",
            "best_model = grid_search.best_estimator_\n",
            "y_pred = best_model.predict(X_test)",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(classification_report(y_test, y_pred))\n",
            "\n",
            "matrix = confusion_matrix(y_test, y_pred)\n",
            'sns.heatmap(matrix, cmap="winter", annot=True)\n',
            "plt.show()",
        ],
    },
]

notebook_structure = {
    "cells": notebook_cells,
    "metadata": {
        "language_info": {"name": "python"},
        "orig_nbformat": 4,
    },
    "nbformat": 4,
    "nbformat_minor": 2,
}

output_filename = "prediction_pipeline.ipynb"

with open(output_filename, "w", encoding="utf-8") as f:
    json.dump(notebook_structure, f, indent=2)

print(f"Successfully generated notebook: {output_filename}")